package com.redsamurai.model.views;

import java.sql.PreparedStatement;

import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 19 18:35:57 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }

    @Override
    protected PreparedStatement getPreparedStatement(int noUserParams, boolean[] b) {
        PreparedStatement stmt = null;

        DBTransactionImpl trans = (DBTransactionImpl) this.getDBTransaction();

        String queryStr = buildQuery(noUserParams, false /*forRowCount*/);
        stmt = trans.createPreparedStatement(queryStr, getFetchSize());

        if (stmt != null) {
            this.getDBTransaction()
                .getSQLBuilder()
                .doStatementSetBindingStyle(stmt, getBindingStyle());
        }

        return stmt;
    }
}

